// Shared template data for TemplateShowcase and template detail pages

export interface TemplateData {
  id: string;
  name: string;
  category: string;
  description: string;
  longDescription: string;
  features: string[];
  image: string;
  gallery: string[];
  popular: boolean;
  price: string;
  techStack: string[];
  pages: string[];
}

export const categories = [
  { id: "all", label: "All Templates" },
  { id: "business", label: "Business" },
  { id: "ecommerce", label: "E-commerce" },
  { id: "portfolio", label: "Portfolio" },
  { id: "restaurant", label: "Restaurant" },
  { id: "healthcare", label: "Healthcare" },
  { id: "construction", label: "Construction" },
  { id: "plumbing", label: "Plumbing" },
  { id: "retail", label: "Retail" },
  { id: "legal", label: "Legal" },
  { id: "realestate", label: "Real Estate" },
  { id: "fitness", label: "Fitness" },
  { id: "education", label: "Education" },
];

export const categoryLabels: Record<string, string> = {
  business: "Business",
  ecommerce: "E-commerce",
  portfolio: "Portfolio",
  restaurant: "Restaurant",
  healthcare: "Healthcare",
  construction: "Construction",
  plumbing: "Plumbing",
  retail: "Retail",
  legal: "Legal",
  realestate: "Real Estate",
  fitness: "Fitness",
  education: "Education",
};

export const templates: TemplateData[] = [
  {
    id: "modern-agency",
    name: "Modern Agency",
    category: "business",
    description: "Clean and professional template for digital agencies and consultants.",
    longDescription: "The Modern Agency template is designed for forward-thinking digital agencies, marketing firms, and consultants who want to make a strong first impression. With its clean lines, bold typography, and strategic use of whitespace, this template communicates professionalism and creativity in equal measure.",
    features: ["Responsive Design", "Fast Loading", "SEO Ready", "Contact Forms", "Portfolio Gallery", "Team Section"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/digilab-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/digilab-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/busicol-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/innova-free-template-353x278.jpg",
    ],
    popular: true,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "About", "Services", "Portfolio", "Team", "Contact"],
  },
  {
    id: "shop-starter",
    name: "Shop Starter",
    category: "ecommerce",
    description: "Complete e-commerce solution with cart, checkout, and product pages.",
    longDescription: "Shop Starter is your all-in-one e-commerce solution, perfect for businesses ready to sell online. From product catalogs to secure checkout, this template has everything you need to launch a successful online store.",
    features: ["Shopping Cart", "Payment Ready", "Inventory Management", "Product Filters", "Wishlist", "Order Tracking"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/cozastore-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/cozastore-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/ashion-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/capitalshop-free-template-353x278.jpg",
    ],
    popular: true,
    price: "Included",
    techStack: ["Next.js", "Stripe", "Tailwind CSS"],
    pages: ["Home", "Shop", "Product Detail", "Cart", "Checkout", "Account"],
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    category: "portfolio",
    description: "Showcase your work beautifully with this stunning portfolio template.",
    longDescription: "Creative Portfolio is designed for artists, designers, photographers, and creatives who want their work to take center stage. With stunning galleries, smooth animations, and a minimalist aesthetic, your portfolio will leave a lasting impression.",
    features: ["Image Gallery", "Smooth Animations", "Contact Form", "Project Details", "Lightbox View", "Blog Section"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/work-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/work-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/create-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/photosen-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Framer Motion", "Tailwind CSS"],
    pages: ["Home", "Portfolio", "About", "Services", "Blog", "Contact"],
  },
  {
    id: "tasty-bites",
    name: "Tasty Bites",
    category: "restaurant",
    description: "Perfect for restaurants, cafes, and food businesses.",
    longDescription: "Tasty Bites brings the warmth and flavor of your restaurant to the digital world. With beautiful food photography sections, easy-to-read menus, and integrated reservation systems, your customers can discover and book their next meal with ease.",
    features: ["Menu Display", "Online Reservations", "Photo Gallery", "Location Map", "Opening Hours", "Special Offers"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/feliciano-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/feliciano-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/gourmet-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/tasty-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Google Maps"],
    pages: ["Home", "Menu", "About", "Gallery", "Reservations", "Contact"],
  },
  {
    id: "health-first",
    name: "Health First",
    category: "healthcare",
    description: "Professional template for clinics, doctors, and healthcare providers.",
    longDescription: "Health First is tailored for medical professionals, clinics, and healthcare providers who need to establish trust and credibility online. With clean design, appointment booking features, and easy-to-navigate service pages, patients can find the care they need.",
    features: ["Appointment Booking", "Services Overview", "Doctor Profiles", "Patient Portal", "Insurance Info", "Blog/Resources"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/services-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/services-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/digilab-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/busicol-free-template-353x278.jpg",
    ],
    popular: true,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Calendly"],
    pages: ["Home", "Services", "Doctors", "Appointments", "Blog", "Contact"],
  },
  {
    id: "startup-launch",
    name: "Startup Launch",
    category: "business",
    description: "Modern landing page perfect for SaaS and tech startups.",
    longDescription: "Startup Launch is built for ambitious tech startups and SaaS companies looking to make a splash. With conversion-optimized layouts, feature showcases, pricing tables, and testimonial sections, this template helps you turn visitors into customers.",
    features: ["Hero Section", "Feature Showcase", "Pricing Tables", "Testimonials", "FAQ Section", "Newsletter Signup"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/busicol-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/busicol-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/digilab-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/innova-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Features", "Pricing", "About", "Blog", "Contact"],
  },
  {
    id: "boutique-store",
    name: "Boutique Store",
    category: "ecommerce",
    description: "Elegant online store for fashion, jewelry, and lifestyle brands.",
    longDescription: "Boutique Store is crafted for fashion brands, jewelry designers, and lifestyle businesses that value aesthetics. With elegant product displays, lookbook features, and a sophisticated checkout experience, your brand will shine.",
    features: ["Lookbook Galleries", "Quick View", "Wishlist", "Size Guides", "Related Products", "Customer Reviews"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/ashion-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/ashion-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/cozastore-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/malefashion-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Stripe", "Tailwind CSS"],
    pages: ["Home", "Shop", "Lookbook", "About", "Blog", "Contact"],
  },
  {
    id: "minimal-folio",
    name: "Minimal Folio",
    category: "portfolio",
    description: "Minimalist design that lets your work speak for itself.",
    longDescription: "Minimal Folio embraces the power of simplicity. With a clean, distraction-free design, this template puts your work front and center. Perfect for photographers, designers, and artists who believe less is more.",
    features: ["Fullscreen Gallery", "Lightbox View", "Blog Section", "About Page", "Contact Form", "Social Links"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/create-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/create-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/work-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/portfolio2-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Portfolio", "About", "Blog", "Contact"],
  },
  // New industry templates
  {
    id: "build-pro",
    name: "Build Pro",
    category: "construction",
    description: "Robust template for construction companies and contractors.",
    longDescription: "Build Pro is designed for construction firms, general contractors, and building companies. Showcase your completed projects, highlight your services, and make it easy for clients to request quotes with this professional, trust-building template.",
    features: ["Project Gallery", "Service Areas", "Quote Request", "Team Profiles", "Testimonials", "Contact Form"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Services", "Projects", "About", "Quote", "Contact"],
  },
  {
    id: "pipe-works",
    name: "Pipe Works",
    category: "plumbing",
    description: "Clean template for plumbing and HVAC service businesses.",
    longDescription: "Pipe Works is built for plumbing, HVAC, and home service businesses that need a reliable online presence. With emergency contact features, service area maps, and easy booking, your customers can find and reach you when they need you most.",
    features: ["Service Booking", "Emergency Contact", "Service Areas", "Customer Reviews", "FAQ Section", "Contact Form"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Google Maps"],
    pages: ["Home", "Services", "About", "Reviews", "FAQ", "Contact"],
  },
  {
    id: "shop-front",
    name: "Shop Front",
    category: "retail",
    description: "Modern template for retail stores and local shops.",
    longDescription: "Shop Front brings the charm of your retail business online. Whether you run a boutique, gift shop, or specialty store, this template highlights your products, location, and brand story to attract both local and online customers.",
    features: ["Product Showcase", "Store Locator", "Opening Hours", "Brand Story", "Newsletter Signup", "Contact Form"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Products", "About", "Location", "Blog", "Contact"],
  },
  {
    id: "legal-edge",
    name: "Legal Edge",
    category: "legal",
    description: "Authoritative template for law firms and legal practices.",
    longDescription: "Legal Edge conveys trust, authority, and professionalism for law firms, attorneys, and legal consultants. With practice area pages, attorney profiles, and client testimonials, potential clients can find the legal expertise they need.",
    features: ["Practice Areas", "Attorney Profiles", "Case Results", "Client Testimonials", "Free Consultation", "Blog Section"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Practice Areas", "Attorneys", "Results", "Blog", "Contact"],
  },
  {
    id: "prime-property",
    name: "Prime Property",
    category: "realestate",
    description: "Elegant template for real estate agents and property listings.",
    longDescription: "Prime Property is designed for real estate agents, brokers, and property management companies. With stunning property listings, virtual tour integration, and agent profiles, this template helps you close more deals and build client relationships.",
    features: ["Property Listings", "Search & Filters", "Virtual Tours", "Agent Profiles", "Mortgage Calculator", "Contact Form"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Google Maps"],
    pages: ["Home", "Listings", "Agents", "About", "Blog", "Contact"],
  },
  {
    id: "fit-zone",
    name: "Fit Zone",
    category: "fitness",
    description: "Energetic template for gyms, trainers, and fitness studios.",
    longDescription: "Fit Zone captures the energy and motivation of the fitness industry. Perfect for gyms, personal trainers, yoga studios, and fitness centers, this template showcases classes, trainer profiles, membership plans, and success stories to inspire new members.",
    features: ["Class Schedule", "Trainer Profiles", "Membership Plans", "Success Stories", "Gallery", "Contact Form"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Classes", "Trainers", "Pricing", "Gallery", "Contact"],
  },
  {
    id: "bright-minds",
    name: "Bright Minds",
    category: "education",
    description: "Friendly template for schools, tutors, and educational platforms.",
    longDescription: "Bright Minds is designed for educational institutions, tutoring services, and online learning platforms. With course catalogs, instructor profiles, and enrollment features, this template makes education accessible and engaging for students of all ages.",
    features: ["Course Catalog", "Instructor Profiles", "Enrollment Forms", "Event Calendar", "Resource Library", "Contact Form"],
    image: "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    gallery: [
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
      "https://colorlib.com/wp/wp-content/uploads/sites/2/developer-free-template-353x278.jpg",
    ],
    popular: false,
    price: "Included",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Courses", "Instructors", "Events", "Resources", "Contact"],
  },
];
