// Shared template data for TemplateShowcase and template detail pages

export interface TemplateData {
  id: string;
  name: string;
  category: string;
  description: string;
  longDescription: string;
  features: string[];
  image: string;
  screenshot: string;
  gallery: string[];
  popular: boolean;
  price: string;
  techStack: string[];
  pages: string[];
  demoUrl: string;
}

export interface PriceBreakdownItem {
  label: string;
  value: string;
}

// Generate a real website screenshot URL from a demo URL
function screenshotUrl(demoUrl: string, width = 1200, height = 800): string {
  return `https://image.thum.io/get/width/${width}/crop/${height}/${demoUrl}`;
}

// Price breakdowns by tier — shows what's included and why
const breakdownsByTier: Record<string, PriceBreakdownItem[]> = {
  "700": [
    { label: "Custom Design & Layout", value: "$300" },
    { label: "5 Responsive Pages", value: "$100" },
    { label: "Mobile Optimization", value: "Included" },
    { label: "Basic SEO Setup", value: "$50" },
    { label: "Contact Form Integration", value: "$50" },
    { label: "Performance Optimization", value: "Included" },
    { label: "Hosting Setup & Deployment", value: "$100" },
    { label: "30-Day Support", value: "$100" },
  ],
  "900": [
    { label: "Custom Design & Development", value: "$350" },
    { label: "6 Responsive Pages", value: "$150" },
    { label: "Mobile-First Design", value: "Included" },
    { label: "SEO Optimization Package", value: "$100" },
    { label: "Interactive Features", value: "$100" },
    { label: "CMS Integration", value: "$100" },
    { label: "30-Day Support", value: "$100" },
  ],
  "1200": [
    { label: "Premium Design & Development", value: "$450" },
    { label: "6+ Responsive Pages", value: "$200" },
    { label: "Mobile-First Design", value: "Included" },
    { label: "Advanced SEO Setup", value: "$150" },
    { label: "Booking / Scheduling System", value: "$100" },
    { label: "CMS Integration", value: "$100" },
    { label: "Analytics Integration", value: "Included" },
    { label: "60-Day Priority Support", value: "$200" },
  ],
  "1500": [
    { label: "Complex UI Development", value: "$550" },
    { label: "Dashboard Interface Design", value: "$250" },
    { label: "Real-Time Data Widgets", value: "$200" },
    { label: "Charts & Reporting", value: "$150" },
    { label: "User Management System", value: "$150" },
    { label: "Dark / Light Mode", value: "Included" },
    { label: "60-Day Priority Support", value: "$200" },
  ],
  "1700": [
    { label: "E-Commerce Design & Dev", value: "$500" },
    { label: "Product & Catalog Pages", value: "$250" },
    { label: "Payment Integration (Stripe)", value: "$250" },
    { label: "Shopping Cart & Checkout", value: "$250" },
    { label: "Inventory Management", value: "$150" },
    { label: "Mobile Shopping Experience", value: "Included" },
    { label: "60-Day Priority Support", value: "$300" },
  ],
};

export function getTemplateBreakdown(template: TemplateData): PriceBreakdownItem[] {
  const priceNum = template.price.replace(/[^0-9]/g, "");
  return breakdownsByTier[priceNum] || breakdownsByTier["900"];
}

export const categories = [
  { id: "all", label: "All Templates" },
  { id: "business", label: "Business" },
  { id: "ecommerce", label: "E-commerce" },
  { id: "portfolio", label: "Portfolio" },
  { id: "restaurant", label: "Restaurant" },
  { id: "healthcare", label: "Healthcare" },
  { id: "construction", label: "Construction" },
  { id: "plumbing", label: "Plumbing" },
  { id: "retail", label: "Retail" },
  { id: "legal", label: "Legal" },
  { id: "realestate", label: "Real Estate" },
  { id: "fitness", label: "Fitness" },
  { id: "education", label: "Education" },
  { id: "barbershop", label: "Barber Shop" },
  { id: "landscaping", label: "Landscaping" },
  { id: "remodeling", label: "Remodeling" },
  { id: "dashboard", label: "Dashboard" },
  { id: "automotive", label: "Automotive" },
  { id: "cleaning", label: "Cleaning" },
];

export const categoryLabels: Record<string, string> = {
  business: "Business",
  ecommerce: "E-commerce",
  portfolio: "Portfolio",
  restaurant: "Restaurant",
  healthcare: "Healthcare",
  construction: "Construction",
  plumbing: "Plumbing",
  retail: "Retail",
  legal: "Legal",
  realestate: "Real Estate",
  fitness: "Fitness",
  education: "Education",
  barbershop: "Barber Shop",
  landscaping: "Landscaping",
  remodeling: "Remodeling",
  dashboard: "Dashboard",
  automotive: "Automotive",
  cleaning: "Cleaning",
};

export interface CategoryGroup {
  id: string;
  label: string;
  categories: string[];
}

export const categoryGroups: CategoryGroup[] = [
  { id: "all", label: "All Templates", categories: [] },
  { id: "business-professional", label: "Business", categories: ["business", "legal", "realestate", "dashboard"] },
  { id: "services-trades", label: "Services", categories: ["construction", "plumbing", "landscaping", "remodeling", "automotive", "cleaning"] },
  { id: "health-lifestyle", label: "Lifestyle", categories: ["healthcare", "fitness", "barbershop", "restaurant"] },
  { id: "creative-education", label: "Creative", categories: ["portfolio", "education"] },
  { id: "ecommerce-retail", label: "Shopping", categories: ["ecommerce", "retail"] },
];

export const templates: TemplateData[] = [
  {
    id: "modern-agency",
    name: "Modern Agency",
    category: "business",
    description: "Clean and professional template for digital agencies and consultants.",
    longDescription: "The Modern Agency template is designed for forward-thinking digital agencies, marketing firms, and consultants who want to make a strong first impression. With its clean lines, bold typography, and strategic use of whitespace, this template communicates professionalism and creativity in equal measure.",
    features: ["Responsive Design", "Fast Loading", "SEO Ready", "Contact Forms", "Portfolio Gallery", "Team Section"],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/Orbit/"),
    gallery: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=800&q=80",
    ],
    popular: true,
    price: "From $1,200",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "About", "Services", "Portfolio", "Team", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/Orbit/",
  },
  {
    id: "shop-starter",
    name: "Shop Starter",
    category: "ecommerce",
    description: "Complete e-commerce solution with cart, checkout, and product pages.",
    longDescription: "Shop Starter is your all-in-one e-commerce solution, perfect for businesses ready to sell online. From product catalogs to secure checkout, this template has everything you need to launch a successful online store.",
    features: ["Shopping Cart", "Payment Ready", "Inventory Management", "Product Filters", "Wishlist", "Order Tracking"],
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/eStore/"),
    gallery: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    ],
    popular: true,
    price: "From $1,700",
    techStack: ["Next.js", "Stripe", "Tailwind CSS"],
    pages: ["Home", "Shop", "Product Detail", "Cart", "Checkout", "Account"],
    demoUrl: "https://bootstrapmade.com/demo/eStore/",
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    category: "portfolio",
    description: "Showcase your work beautifully with this stunning portfolio template.",
    longDescription: "Creative Portfolio is designed for artists, designers, photographers, and creatives who want their work to take center stage. With stunning galleries, smooth animations, and a minimalist aesthetic, your portfolio will leave a lasting impression.",
    features: ["Image Gallery", "Smooth Animations", "Contact Form", "Project Details", "Lightbox View", "Blog Section"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://html5up.net/uploads/demos/paradigm-shift/"),
    gallery: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $900",
    techStack: ["Next.js", "Framer Motion", "Tailwind CSS"],
    pages: ["Home", "Portfolio", "About", "Services", "Blog", "Contact"],
    demoUrl: "https://html5up.net/uploads/demos/paradigm-shift/",
  },
  {
    id: "tasty-bites",
    name: "Tasty Bites",
    category: "restaurant",
    description: "Perfect for restaurants, cafes, and food businesses.",
    longDescription: "Tasty Bites brings the warmth and flavor of your restaurant to the digital world. With beautiful food photography sections, easy-to-read menus, and integrated reservation systems, your customers can discover and book their next meal with ease.",
    features: ["Menu Display", "Online Reservations", "Photo Gallery", "Location Map", "Opening Hours", "Special Offers"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/Savora/"),
    gallery: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $900",
    techStack: ["Next.js", "Tailwind CSS", "Google Maps"],
    pages: ["Home", "Menu", "About", "Gallery", "Reservations", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/Savora/",
  },
  {
    id: "health-first",
    name: "Health First",
    category: "healthcare",
    description: "Professional template for clinics, doctors, and healthcare providers.",
    longDescription: "Health First is tailored for medical professionals, clinics, and healthcare providers who need to establish trust and credibility online. With clean design, appointment booking features, and easy-to-navigate service pages, patients can find the care they need.",
    features: ["Appointment Booking", "Services Overview", "Doctor Profiles", "Patient Portal", "Insurance Info", "Blog/Resources"],
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/MediNest/"),
    gallery: [
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1666214280557-f1b5022eb634?auto=format&fit=crop&w=800&q=80",
    ],
    popular: true,
    price: "From $1,200",
    techStack: ["Next.js", "Tailwind CSS", "Calendly"],
    pages: ["Home", "Services", "Doctors", "Appointments", "Blog", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/MediNest/",
  },
  {
    id: "startup-launch",
    name: "Startup Launch",
    category: "business",
    description: "Modern landing page perfect for SaaS and tech startups.",
    longDescription: "Startup Launch is built for ambitious tech startups and SaaS companies looking to make a splash. With conversion-optimized layouts, feature showcases, pricing tables, and testimonial sections, this template helps you turn visitors into customers.",
    features: ["Hero Section", "Feature Showcase", "Pricing Tables", "Testimonials", "FAQ Section", "Newsletter Signup"],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/Landify/"),
    gallery: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $900",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Features", "Pricing", "About", "Blog", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/Landify/",
  },
  {
    id: "boutique-store",
    name: "Boutique Store",
    category: "ecommerce",
    description: "Elegant online store for fashion, jewelry, and lifestyle brands.",
    longDescription: "Boutique Store is crafted for fashion brands, jewelry designers, and lifestyle businesses that value aesthetics. With elegant product displays, lookbook features, and a sophisticated checkout experience, your brand will shine.",
    features: ["Lookbook Galleries", "Quick View", "Wishlist", "Size Guides", "Related Products", "Customer Reviews"],
    image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://builder.bootstrapmade.com/demo/FashionStore/"),
    gallery: [
      "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $1,700",
    techStack: ["Next.js", "Stripe", "Tailwind CSS"],
    pages: ["Home", "Shop", "Lookbook", "About", "Blog", "Contact"],
    demoUrl: "https://builder.bootstrapmade.com/demo/FashionStore/",
  },
  {
    id: "minimal-folio",
    name: "Minimal Folio",
    category: "portfolio",
    description: "Minimalist design that lets your work speak for itself.",
    longDescription: "Minimal Folio embraces the power of simplicity. With a clean, distraction-free design, this template puts your work front and center. Perfect for photographers, designers, and artists who believe less is more.",
    features: ["Fullscreen Gallery", "Lightbox View", "Blog Section", "About Page", "Contact Form", "Social Links"],
    image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/MinimalFolio/"),
    gallery: [
      "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $700",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Portfolio", "About", "Blog", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/MinimalFolio/",
  },
  {
    id: "build-pro",
    name: "Build Pro",
    category: "construction",
    description: "Robust template for construction companies and contractors.",
    longDescription: "Build Pro is designed for construction firms, general contractors, and building companies. Showcase your completed projects, highlight your services, and make it easy for clients to request quotes with this professional, trust-building template.",
    features: ["Project Gallery", "Service Areas", "Quote Request", "Team Profiles", "Testimonials", "Contact Form"],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/Constructo/"),
    gallery: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $900",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Services", "Projects", "About", "Quote", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/Constructo/",
  },
  {
    id: "pipe-works",
    name: "Pipe Works",
    category: "plumbing",
    description: "Clean template for plumbing and HVAC service businesses.",
    longDescription: "Pipe Works is built for plumbing, HVAC, and home service businesses that need a reliable online presence. With emergency contact features, service area maps, and easy booking, your customers can find and reach you when they need you most.",
    features: ["Service Booking", "Emergency Contact", "Service Areas", "Customer Reviews", "FAQ Section", "Contact Form"],
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/FlexBiz/"),
    gallery: [
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $700",
    techStack: ["Next.js", "Tailwind CSS", "Google Maps"],
    pages: ["Home", "Services", "About", "Reviews", "FAQ", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/FlexBiz/",
  },
  {
    id: "shop-front",
    name: "Shop Front",
    category: "retail",
    description: "Modern template for retail stores and local shops.",
    longDescription: "Shop Front brings the charm of your retail business online. Whether you run a boutique, gift shop, or specialty store, this template highlights your products, location, and brand story to attract both local and online customers.",
    features: ["Product Showcase", "Store Locator", "Opening Hours", "Brand Story", "Newsletter Signup", "Contact Form"],
    image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://startbootstrap.github.io/startbootstrap-shop-homepage/"),
    gallery: [
      "https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1528698827591-e19cef791f48?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $900",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Products", "About", "Location", "Blog", "Contact"],
    demoUrl: "https://startbootstrap.github.io/startbootstrap-shop-homepage/",
  },
  {
    id: "legal-edge",
    name: "Legal Edge",
    category: "legal",
    description: "Authoritative template for law firms and legal practices.",
    longDescription: "Legal Edge conveys trust, authority, and professionalism for law firms, attorneys, and legal consultants. With practice area pages, attorney profiles, and client testimonials, potential clients can find the legal expertise they need.",
    features: ["Practice Areas", "Attorney Profiles", "Case Results", "Client Testimonials", "Free Consultation", "Blog Section"],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/Arsha/"),
    gallery: [
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $1,200",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Practice Areas", "Attorneys", "Results", "Blog", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/Arsha/",
  },
  {
    id: "prime-property",
    name: "Prime Property",
    category: "realestate",
    description: "Elegant template for real estate agents and property listings.",
    longDescription: "Prime Property is designed for real estate agents, brokers, and property management companies. With stunning property listings, virtual tour integration, and agent profiles, this template helps you close more deals and build client relationships.",
    features: ["Property Listings", "Search & Filters", "Virtual Tours", "Agent Profiles", "Mortgage Calculator", "Contact Form"],
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/TheProperty/"),
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $1,200",
    techStack: ["Next.js", "Tailwind CSS", "Google Maps"],
    pages: ["Home", "Listings", "Agents", "About", "Blog", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/TheProperty/",
  },
  {
    id: "fit-zone",
    name: "Fit Zone",
    category: "fitness",
    description: "Energetic template for gyms, trainers, and fitness studios.",
    longDescription: "Fit Zone captures the energy and motivation of the fitness industry. Perfect for gyms, personal trainers, yoga studios, and fitness centers, this template showcases classes, trainer profiles, membership plans, and success stories to inspire new members.",
    features: ["Class Schedule", "Trainer Profiles", "Membership Plans", "Success Stories", "Gallery", "Contact Form"],
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://themewagon.github.io/gymlife/"),
    gallery: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $900",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Classes", "Trainers", "Pricing", "Gallery", "Contact"],
    demoUrl: "https://themewagon.github.io/gymlife/",
  },
  {
    id: "bright-minds",
    name: "Bright Minds",
    category: "education",
    description: "Friendly template for schools, tutors, and educational platforms.",
    longDescription: "Bright Minds is designed for educational institutions, tutoring services, and online learning platforms. With course catalogs, instructor profiles, and enrollment features, this template makes education accessible and engaging for students of all ages.",
    features: ["Course Catalog", "Instructor Profiles", "Enrollment Forms", "Event Calendar", "Resource Library", "Contact Form"],
    image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/Learner/"),
    gallery: [
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1523050854058-8df90110c8f1?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $900",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Courses", "Instructors", "Events", "Resources", "Contact"],
    demoUrl: "https://bootstrapmade.com/demo/Learner/",
  },
  {
    id: "sharp-cuts",
    name: "Sharp Cuts",
    category: "barbershop",
    description: "Stylish template for barber shops, salons, and grooming studios.",
    longDescription: "Sharp Cuts is designed for barber shops, hair salons, and grooming studios that want to showcase their style and craftsmanship. With service menus, booking integration, gallery of cuts, and team profiles, this template helps you attract new clients and build your brand.",
    features: ["Service Menu", "Online Booking", "Gallery of Cuts", "Team Profiles", "Price List", "Contact Form"],
    image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://themewagon.github.io/brber/"),
    gallery: [
      "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1585747860874-05cbb6c4b9c0?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $700",
    techStack: ["Next.js", "Tailwind CSS", "Calendly"],
    pages: ["Home", "Services", "Gallery", "Team", "Pricing", "Contact"],
    demoUrl: "https://themewagon.github.io/brber/",
  },
  {
    id: "green-scapes",
    name: "Green Scapes",
    category: "landscaping",
    description: "Professional template for landscaping, lawn care, and tree services.",
    longDescription: "Green Scapes is built for landscaping companies, lawn care providers, and tree service businesses. Showcase your outdoor projects, highlight seasonal services, and make it easy for homeowners to request free estimates with this nature-inspired template.",
    features: ["Project Gallery", "Service Areas", "Free Estimate Form", "Seasonal Services", "Before & After Photos", "Testimonials"],
    image: "https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://themewagon.github.io/landscaper/"),
    gallery: [
      "https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $700",
    techStack: ["Next.js", "Tailwind CSS", "Google Maps"],
    pages: ["Home", "Services", "Projects", "About", "Estimate", "Contact"],
    demoUrl: "https://themewagon.github.io/landscaper/",
  },
  {
    id: "home-revamp",
    name: "Home Revamp",
    category: "remodeling",
    description: "Elegant template for home remodeling, renovation, and interior design.",
    longDescription: "Home Revamp is crafted for home remodeling contractors, renovation companies, and interior designers. With before-and-after project galleries, service breakdowns, and appointment scheduling, this template helps you win more renovation projects.",
    features: ["Before & After Gallery", "Appointment Booking", "Service Breakdown", "Project Portfolio", "Client Reviews", "Contact Form"],
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://themewagon.github.io/apex/"),
    gallery: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $900",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Services", "Projects", "About", "Appointments", "Contact"],
    demoUrl: "https://themewagon.github.io/apex/",
  },
  {
    id: "biz-dashboard",
    name: "Biz Dashboard",
    category: "dashboard",
    description: "Modern admin dashboard for business analytics and management.",
    longDescription: "Biz Dashboard is a sleek, data-driven admin template for businesses that need to monitor KPIs, manage operations, and visualize data. With interactive charts, data tables, and real-time widgets, this dashboard puts your business metrics at your fingertips.",
    features: ["Analytics Charts", "Data Tables", "Real-time Widgets", "User Management", "Dark/Light Mode", "Notifications"],
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://bootstrapmade.com/demo/NiceAdmin/"),
    gallery: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=800&q=80",
    ],
    popular: true,
    price: "From $1,500",
    techStack: ["Next.js", "Tailwind CSS", "Chart.js"],
    pages: ["Dashboard", "Analytics", "Users", "Settings", "Reports", "Profile"],
    demoUrl: "https://bootstrapmade.com/demo/NiceAdmin/",
  },
  {
    id: "auto-fix",
    name: "Auto Fix",
    category: "automotive",
    description: "Bold template for auto repair shops, mechanics, and car services.",
    longDescription: "Auto Fix is built for auto repair shops, mechanics, and car service centers. With service listings, online booking, technician profiles, and customer testimonials, this template helps you build trust and fill your appointment book.",
    features: ["Service Listings", "Online Booking", "Technician Profiles", "Customer Reviews", "Price Estimates", "Contact Form"],
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://themewagon.github.io/carserv/"),
    gallery: [
      "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1625047509168-a7026f36de04?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $700",
    techStack: ["Next.js", "Tailwind CSS", "Google Maps"],
    pages: ["Home", "Services", "Technicians", "About", "Booking", "Contact"],
    demoUrl: "https://themewagon.github.io/carserv/",
  },
  {
    id: "sparkle-clean",
    name: "Sparkle Clean",
    category: "cleaning",
    description: "Fresh template for cleaning companies and maintenance services.",
    longDescription: "Sparkle Clean is designed for cleaning companies, janitorial services, and maintenance businesses. With service packages, instant quote forms, and trust-building testimonials, this template helps you stand out in a competitive market and win recurring clients.",
    features: ["Service Packages", "Instant Quote", "Before & After Photos", "Trust Badges", "Testimonials", "Contact Form"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80",
    screenshot: screenshotUrl("https://themewagon.github.io/cleaning-company/"),
    gallery: [
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=800&q=80",
    ],
    popular: false,
    price: "From $700",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    pages: ["Home", "Services", "About", "Gallery", "Quote", "Contact"],
    demoUrl: "https://themewagon.github.io/cleaning-company/",
  },
];
